[package]
name = "chirpstack-concentratord-2g4"
repository="https://github.com/chirpstack/chirpstack-concentratord/"
license="MIT"
version = "4.0.0-rc.1"
authors = ["Orne Brocaar <info@brocaar.com>"]
edition = "2018"
publish = false

[dependencies]
libloragw-2g4 = {path = "../libloragw-2g4"}
libconcentratord = {path = "../libconcentratord"}
chirpstack_api = { version = "4.0.0-rc.1", default-features = false }
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
clap = "2.33"
log = "0.4"
simple_logger = "1.11"
zmq = "0.9"
hex = "0.4"
lazy_static = "1.4"
chrono = "0.4"
humantime-serde = "1.0"
syslog = "5.0"
prost = "0.10"
pbjson-types = "0.3.2"
signal-hook = "0.3"
handlebars = "4.1"
rand = "0.8"

[features]
default = ['zmq/vendored']
