[workspace]
members = [
	"chirpstack-concentratord-sx1301",
	"chirpstack-concentratord-sx1302",
	"chirpstack-udp-bridge",
	"gateway-id",
	"libloragw-sx1301",
	"libloragw-sx1302",
	"libconcentratord",
]
