[workspace]
members = [
	"chirpstack-concentratord-sx1301",
	"chirpstack-concentratord-sx1302",
	"libloragw-sx1301",
	"libloragw-sx1302",
	"libconcentratord",
]

[profile.release]
panic = "abort"
lto = true
