version: "2"
services:
  chirpstack-concentratord:
    build:
      context: .
      dockerfile: Dockerfile-devel
    volumes:
      - ./:/chirpstack-concentratord
      - ./.rust/target:/chirpstack-concentratord/target
      - ./.rust/.cargo/registry/index:/usr/local/cargo/registry/index
      - ./.rust/.cargo/registry/cache:/usr/local/cargo/registry/cache
      - ./.rust/.cargo/git/db:/usr/local/cargo/git/db
