version: "2"
services:
  chirpstack-concentratord:
    build:
      context: .
      dockerfile: Dockerfile-devel
    volumes:
      - ./:/chirpstack-concentratord
      - /home/brocaar/Work/Projects/ChirpStack/Repos/chirpstack-api/:/chirpstack-api
