[package]
name = "gateway-id"
repository="https://github.com/brocaar/chirpstack-concentratord/"
license="MIT"
version = "4.1.0-test.1"
authors = ["Orne Brocaar <info@brocaar.com>"]
edition = "2018"
publish = false

[dependencies]
zmq = "0.10"
clap = "2.33"
hex = "0.4"
