[package]
name = "gateway-id"
repository="https://github.com/brocaar/chirpstack-concentratord/"
license="MIT"
version = "3.3.3"
authors = ["Orne Brocaar <info@brocaar.com>"]
edition = "2018"
publish = false

[dependencies]
zmq = "0.9"
clap = "2.33"
hex = "0.4"

[features]
default = ['zmq/vendored']
