[package]
name = "chirpstack-concentratord-sx1301"
version = "3.0.0-test.1"
authors = ["Orne Brocaar <info@brocaar.com>"]
edition = "2018"
publish = false

[dependencies]
libloragw-sx1301 = {path = "../libloragw-sx1301"}
jitqueue = {path = "../jitqueue"}
chirpstack_api = { version = "3.0.4", default-features = false }
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
clap = "2.33.0"
log = "0.4.8"
simple_logger = "1.3.0"
zmq = "0.9.1"
protobuf = "2.8.1"
hex = "0.3.2"
lazy_static = "1.4"
uuid = { version = "0.8.1", features = ["v4"] }
chrono = "0.4"
humantime-serde = "0.1.1"

[features]
default = ['zmq/vendored']
