[package]
name = "chirpstack-concentratord-sx1301"
repository="https://github.com/chirpstack/chirpstack-concentratord/"
license="MIT"
version = "4.0.0"
authors = ["Orne Brocaar <info@brocaar.com>"]
edition = "2018"
publish = false

[dependencies]
libloragw-sx1301 = {path = "../libloragw-sx1301"}
libconcentratord = {path = "../libconcentratord"}
chirpstack_api = { version = "4.0.2", default-features = false }
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
clap = "3.2"
log = "0.4"
simple_logger = "2.3"
zmq = "0.9"
hex = "0.4"
lazy_static = "1.4"
chrono = "0.4"
humantime-serde = "1.1"
syslog = "6.0"
prost = "0.11"
pbjson-types = "0.5"
signal-hook = "0.3"
handlebars = "4.3"
rand = "0.8"

[features]
default = ['zmq/vendored']
