[package]
name = "libconcentratord"
version = "1.0.1"
authors = ["Orne Brocaar <@brocaar.com>"]
edition = "2018"
publish = false

[dependencies]
log = "0.4"
zmq = "0.9.1"
lazy_static = "1.4"
chirpstack_api = { version = "3.1.0", default-features = false }
uuid = { version = "0.8.1", features = ["v4"] }
prost = "0.6"
prost-types = "0.6"

[features]
default = ['zmq/vendored']
