[package]
name = "libconcentratord"
version = "1.0.0"
authors = ["Orne Brocaar <@brocaar.com>"]
edition = "2018"
publish = false

[dependencies]
log = "0.4"
zmq = "0.9.1"
lazy_static = "1.4"
chirpstack_api = { version = "3.0.5", default-features = false }
uuid = { version = "0.8.1", features = ["v4"] }
protobuf = "2.8.1"

[features]
default = ['zmq/vendored']
