[package]
name = "chirpstack-concentratord-sx1302"
version = "3.0.0-test.11"
authors = ["Orne Brocaar <info@brocaar.com>"]
edition = "2018"
publish = false

[dependencies]
libloragw-sx1302 = {path = "../libloragw-sx1302"}
libconcentratord = {path = "../libconcentratord"}
chirpstack_api = { version = "3.5.2", default-features = false }
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
clap = "2.33.0"
log = "0.4.8"
simple_logger = "1.3.0"
zmq = "0.9.1"
hex = "0.4.0"
lazy_static = "1.4"
uuid = { version = "0.8.1", features = ["v4"] }
chrono = "0.4"
humantime-serde = "0.1.1"
syslog = "5.0.0"
prost = "0.6.1"
prost-types = "0.6.1"
signal-hook = "0.1.13"

[features]
default = ['zmq/vendored']
